- hosts: KAFKA-AWS
  any_errors_fatal: true
  pre_tasks:
    - include_vars: /local/apps/idsuser/SPDJIEnvironmentSetup/ansible/environments_old/cross_env_vars.yml
    - include_vars: /local/apps/idsuser/SPDJIEnvironmentSetup/ansible/environments_old/KAFKA/main.yml
#    - include_vars: /local/apps/idsuser/SPDJIEnvironmentSetup/ansible/environments/CARE/DEV/group_vars/main.yml
  roles:
    - role: spdji_install_kafka
