# Get confirmation from user before continue  
- hosts: primary_calc
  vars_prompt:
    - name: "is_continue"
      prompt: "Do you want to continue (Y/N)?"
      default: "N"
      private: no
  tasks:
    - name: Exit if user does not want to continue
      fail: msg="User does not  want to continue, exiting play - {{ is_continue }}"
      when: is_continue | upper != "Y"

#Install Java and WebLogic in all servers
- hosts:  managed_servers
  any_errors_fatal: true
  roles:
    - role: install_java
    - role: install_wls
      
