---
- name: Create zookeeper instance directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "{{ zookeeper_instance }}"
    - "{{ zookeeper_instance }}/bin"
    - "{{ zookeeper_instance }}/conf"
    - "{{ zookeeper_instance }}/zkdata"

- name: Copy static config files
  copy:
    src: "{{ item }}"
    dest: "{{ zookeeper_instance }}/conf"
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "log4j.properties"
    - "configuration.xsl"

- name: Copy executable scripts
  copy:
    src: "{{ zookeeper_installation }}/bin/{{ item }}"
    dest: "{{ zookeeper_instance }}/bin"
    mode: "{{ folder_permission }}"
    remote_src: True
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "zkServer.sh"
    - "zkEnv.sh"
    - "zkCli.sh"
    - "zkCleanup.sh"

- name: Copy environment files
  template:
    src: "{{ item }}.j2"
    dest: "{{ zookeeper_instance }}/conf/{{ item }}"
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "zookeeper-env.sh"
    - "java.env"
    - "zoo.cfg"

- name: Copy Start/stop script file
  template:
    src: "{{ item }}.j2"
    dest: "{{ zookeeper_instance }}/bin/{{ item }}"
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "start.sh"
    - "stop.sh"

- name: Copy id file
  template:
    src: "myid.j2"
    dest: "{{ zookeeper_instance }}/zkdata/myid"
    mode: "{{ folder_permission }}"

- name: Start ZooKeeper instance
  shell: "{{ item }}"
  args:
    chdir: "{{ zookeeper_instance }}/bin"
  with_items:
      - "./start.sh"

...
