- name: Create directory structure
  file:
    path:  "{{ item }}"
    state: directory
    mode:  "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "{{ kafka_home_directory }}"

- name: Extracting Kafka
  unarchive:
    src="kafka_2.12-0.10.2.0.tgz"
    dest="{{ kafka_home_directory }}"
