---
- name: Create solr instance directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "{{ solr_instance }}"
    - "{{ solr_instance }}/bin"
    - "{{ solr_instance }}/conf"
    - "{{ solr_instance }}/logs"
    - "{{ solr_instance }}/data"

- name: Copy solr.xml file to instances home
  copy:
    src: "solr.xml"
    dest: "{{ solr_instance }}/data"
    mode: "{{ folder_permission }}"

- name: Copy static config files
  copy:
    src: "{{ item }}"
    dest: "{{ solr_instance }}/conf/{{ item }}"
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "log4j.properties"
        
- name: Copy script files
  template:
    src: "{{ item }}.j2"
    dest: "{{ solr_instance }}/bin/{{ item }}"
    mode: "{{ folder_permission }}"
  when: not( ("{{ item }}" is undefined) or ("{{ item }}" is none) or ("{{ item }}" | trim=='') )
  with_items:
    - "solr"
    - "solr.in.sh"
    - "start.sh"
    - "stop.sh"

- name: Start Solr instance
  shell: "{{ item }}"
  args:
    chdir: "{{ solr_instance }}/bin"
  with_items:
      - "./start.sh"

...
